set_property IOSTANDARD LVCMOS33 [get_ports clk_2m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_20m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_125m]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property PACKAGE_PIN U2 [get_ports sys_rst_n]
set_property PACKAGE_PIN P17 [get_ports clk_2m]
set_property PACKAGE_PIN Y19 [get_ports clk_20m]
set_property PACKAGE_PIN Y19 [get_ports clk_125m]

set_property IOSTANDARD LVCMOS33 [get_ports clk_10m]
set_property PACKAGE_PIN R18 [get_ports clk_10m]

set_property PACKAGE_PIN V20 [get_ports clk_80m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_80m]

set_property IOSTANDARD LVCMOS33 [get_ports {da_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk]
set_property IOSTANDARD LVCMOS33 [get_ports da_wrt]
set_property PACKAGE_PIN P14 [get_ports da_clk]
set_property PACKAGE_PIN R14 [get_ports da_wrt]
set_property PACKAGE_PIN V9 [get_ports {da_data[0]}]
set_property PACKAGE_PIN W9 [get_ports {da_data[1]}]
set_property PACKAGE_PIN Y9 [get_ports {da_data[2]}]
set_property PACKAGE_PIN V8 [get_ports {da_data[3]}]
set_property PACKAGE_PIN U7 [get_ports {da_data[4]}]
set_property PACKAGE_PIN AB7 [get_ports {da_data[5]}]
set_property PACKAGE_PIN V7 [get_ports {da_data[6]}]
set_property PACKAGE_PIN AB6 [get_ports {da_data[7]}]
set_property PACKAGE_PIN AB8 [get_ports {da_data[8]}]
set_property PACKAGE_PIN AA8 [get_ports {da_data[9]}]
set_property PACKAGE_PIN Y8 [get_ports {da_data[10]}]
set_property PACKAGE_PIN Y7 [get_ports {da_data[11]}]
set_property PACKAGE_PIN N14 [get_ports {da_data[12]}]
set_property PACKAGE_PIN N13 [get_ports {da_data[13]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50m]


set_property PACKAGE_PIN M13 [get_ports {da_data2[0]}]
set_property PACKAGE_PIN K14 [get_ports {da_data2[1]}]
set_property PACKAGE_PIN R17 [get_ports {da_data2[2]}]
set_property PACKAGE_PIN J16 [get_ports {da_data2[3]}]
set_property PACKAGE_PIN N15 [get_ports {da_data2[4]}]
set_property PACKAGE_PIN P19 [get_ports {da_data2[5]}]
set_property PACKAGE_PIN M17 [get_ports {da_data2[6]}]
set_property PACKAGE_PIN P20 [get_ports {da_data2[7]}]
set_property PACKAGE_PIN M16 [get_ports {da_data2[8]}]
set_property PACKAGE_PIN M15 [get_ports {da_data2[9]}]
set_property PACKAGE_PIN L15 [get_ports {da_data2[10]}]
set_property PACKAGE_PIN L14 [get_ports {da_data2[11]}]
set_property PACKAGE_PIN J17 [get_ports {da_data2[12]}]
set_property PACKAGE_PIN K17 [get_ports {da_data2[13]}]
set_property PACKAGE_PIN K18 [get_ports da_clk2]
set_property PACKAGE_PIN K19 [get_ports da_wrt2]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk2]
set_property IOSTANDARD LVCMOS33 [get_ports da_wrt2]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data2[0]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN H15 [get_ports {seg_led[0]}]
set_property PACKAGE_PIN G16 [get_ports {seg_led[1]}]
set_property PACKAGE_PIN L13 [get_ports {seg_led[2]}]
set_property PACKAGE_PIN G15 [get_ports {seg_led[3]}]
set_property PACKAGE_PIN K13 [get_ports {seg_led[4]}]
set_property PACKAGE_PIN G13 [get_ports {seg_led[5]}]
set_property PACKAGE_PIN H14 [get_ports {seg_led[6]}]
set_property PACKAGE_PIN J14 [get_ports {seg_led[7]}]
set_property PACKAGE_PIN J15 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN H17 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN H13 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN G17 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN H18 [get_ports {seg_sel[4]}]
set_property PACKAGE_PIN G18 [get_ports {seg_sel[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_1]
set_property PACKAGE_PIN R16 [get_ports clk_1]

set_property PACKAGE_PIN R16 [get_ports clk_1Hz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_1Hz]

set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property PACKAGE_PIN T1 [get_ports {key[0]}]
set_property PACKAGE_PIN U1 [get_ports {key[1]}]
set_property PACKAGE_PIN W2 [get_ports {key[2]}]
set_property PACKAGE_PIN T3 [get_ports {key[3]}]

set_property CFGBVS VCCO [current_design] set_property CONFIG_VOLTAGE 3.3 [current_design] set_property BITSTREAM.GENERAL.COMPRESS true [current_design] set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]


