# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/TL/ALter/CodeForPost/FPGAXilinxCode/verilog_prj/test_xulie2/exp_da.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
# IP: The module: 'blk_mem_gen_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TL/ALter/CodeForPost/FPGAXilinxCode/verilog_prj/test_xulie2/exp_da.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/TL/ALter/CodeForPost/FPGAXilinxCode/verilog_prj/test_xulie2/exp_da.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
# IP: The module: 'blk_mem_gen_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TL/ALter/CodeForPost/FPGAXilinxCode/verilog_prj/test_xulie2/exp_da.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
